In [1]:
import numpy as np

In [2]:
# ndarray就是n维数组对象
# 创建ndarray最简单的办法是用array()函数，她接受（列表、元组等）作为输入

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array((2, 4, 5, 7))

array([2, 4, 5, 7])

In [4]:
# 嵌套列表可以转换成一个多维数组
# 数组元素等长和不等得到的结果是不一样的类型
# 等长得到的是多维数组，不等长得到的是对象数组
np.array([[1, 2, 3, 5], [2 , 3, 4, 1]])

array([[1, 2, 3, 5],
       [2, 3, 4, 1]])

In [5]:
np.array([[1, 3, 5, 7], [2, 2, 3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
# ndarray 一旦创建，读者可以通过对象属性获取数组的一些信息。
# 例如，ndim 属性可以获取维度，shape 属性可以获取每个维度具体的长度
arr1 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])

In [ ]:
arr1.ndim

In [ ]:
arr1.shape

ndarray 除了存储常见的数值类型数据，还可以存储 Python 其他的常见数据类型，如字符串、逻辑值。默认情况下，NumPy 的 array() 函数会自动为输入序列选择一个合适的数据类型，类型值会被保存在一个称为 dtype 的特殊对象中，它同样可以以属性的形式访问。

In [ ]:
arr1.dtype

In [ ]:
arr2 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])

In [ ]:
arr2.dtype

一般在数据分析操作的对象是数值型的数组，为了方便一些常用数组的创建，NumPy 提供了专门的函数。例如，zeros() 函数可以创建全 0 数组，ones() 函数可以创建全 1 数组，empty() 函数可以创建空数组。使用这些函数时只需要传入一个表示形状的数值或元组

In [ ]:
np.ones(5)

In [ ]:
np.empty((2, 5))

In [ ]:
np.zeros((2, 3, 4))

In [ ]:
# 字符串数组存储的数据如果都是数字，我们常将它转换为数值型，
# 这一点可以通过 ndarray 对象的 astype() 方法实现
num_string = np.array(['1.1', '2.2', '3.3'], dtype=np.string_)

In [ ]:
num_string, num_string.astype(float)

In [ ]:
num_string.astype(float).astype(np.int32)

数组运算，利用numpy，用户可以在不使用循环的情况下对数据进行批量运算，该特性称向量化计算。向量化计算意味着大小相同的数组之间任何算数运算都会应用到其成对的元素。


In [ ]:
arr = np.array([[2., 3., 4.], [4, 5.4, 6]])
arr

In [ ]:
arr * arr

In [ ]:
arr ** 2

In [ ]:
arr - arr

In [ ]:
arr / arr

In [ ]:
arr + arr

当上述操作是某一方的标量时（或者维度更低），Numpy会自动进行填充，将标量的维度扩展到与ndarray数组一直，然后进行向量化运算。该方式称为广播机制。

In [ ]:
1 + np.array([2, 3, 4])

In [ ]:
1 - np.array([2, 3, 4])

当Numpy遇到这种情况时，它首先将1转变为ndarry[1, 1, 1],然后进行运算

In [ ]:
np.array([1, 1, 1]) - np.array([2, 3, 4])

如果运算的两个数组，NumPy会尝试同时填充两个数组，使其维度一致，如果不能使得维度一致，则抛出错误

In [ ]:
np.array([1, 1]) + np.array([2, 3, 4])

ndarray 数组之间除了进行算术运算，还能进行比较操作，得到的结果是相同维度的布尔型数组。注意它们比较的方式也是成对地，即按元素比较。

In [ ]:
np.array([5, 1, 7, 2]) > np.array([2, 3, 4, 5])

In [13]:
x = np.arange(-5, 2, 0.01)
y = np.arange(-20, -10, 0.2)


In [14]:
x

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [15]:
y

array([-20. , -19.8, -19.6, -19.4, -19.2, -19. , -18.8, -18.6, -18.4,
       -18.2, -18. , -17.8, -17.6, -17.4, -17.2, -17. , -16.8, -16.6,
       -16.4, -16.2, -16. , -15.8, -15.6, -15.4, -15.2, -15. , -14.8,
       -14.6, -14.4, -14.2, -14. , -13.8, -13.6, -13.4, -13.2, -13. ,
       -12.8, -12.6, -12.4, -12.2, -12. , -11.8, -11.6, -11.4, -11.2,
       -11. , -10.8, -10.6, -10.4, -10.2])

In [8]:
xspace, yspace = np.meshgrid(x, y)

In [9]:
xspace

array([[-5.  , -4.99, -4.98, ...,  1.97,  1.98,  1.99],
       [-5.  , -4.99, -4.98, ...,  1.97,  1.98,  1.99],
       [-5.  , -4.99, -4.98, ...,  1.97,  1.98,  1.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  1.97,  1.98,  1.99],
       [-5.  , -4.99, -4.98, ...,  1.97,  1.98,  1.99],
       [-5.  , -4.99, -4.98, ...,  1.97,  1.98,  1.99]])

In [10]:
yspace

array([[-20. , -20. , -20. , ..., -20. , -20. , -20. ],
       [-19.8, -19.8, -19.8, ..., -19.8, -19.8, -19.8],
       [-19.6, -19.6, -19.6, ..., -19.6, -19.6, -19.6],
       ...,
       [-10.6, -10.6, -10.6, ..., -10.6, -10.6, -10.6],
       [-10.4, -10.4, -10.4, ..., -10.4, -10.4, -10.4],
       [-10.2, -10.2, -10.2, ..., -10.2, -10.2, -10.2]])

In [20]:
xspace + yspace **2

array([[395.  , 395.01, 395.02, ..., 401.97, 401.98, 401.99],
       [387.04, 387.05, 387.06, ..., 394.01, 394.02, 394.03],
       [379.16, 379.17, 379.18, ..., 386.13, 386.14, 386.15],
       ...,
       [107.36, 107.37, 107.38, ..., 114.33, 114.34, 114.35],
       [103.16, 103.17, 103.18, ..., 110.13, 110.14, 110.15],
       [ 99.04,  99.05,  99.06, ..., 106.01, 106.02, 106.03]])

In [29]:
# meshgrid()函数接受两个一维ndarray，产生两个二维矩阵，他们分别对应两个ndarry的元素对
x = np.arange(-5, -2, 1)
y = np.arange(-20, -15, 1)
xspace, yspace = np.meshgrid(x, y)

In [30]:
x, xspace

(array([-5, -4, -3]),
 array([[-5, -4, -3],
        [-5, -4, -3],
        [-5, -4, -3],
        [-5, -4, -3],
        [-5, -4, -3]]))

In [31]:
y, yspace

(array([-20, -19, -18, -17, -16]),
 array([[-20, -20, -20],
        [-19, -19, -19],
        [-18, -18, -18],
        [-17, -17, -17],
        [-16, -16, -16]]))

In [33]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
arr[5]

5

In [35]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [37]:
arr[5:10] = 2
arr

array([ 0,  1,  2,  3,  4,  2,  2,  2,  2,  2, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
ls = [i for i in range(10)]
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
ls2 = ls[4:8]
ls2

[4, 5, 6, 7]

In [45]:
arr2 = arr[4:8]
arr2

array([4, 5, 6, 7])

在python的列表中，python会对切片的数据重新生成一份拷贝，然后将变量ls2指向这个新的拷贝数据；而NumPy数据进行切片时它只是把原始的数据对应的位置指向变量arr2

In [48]:
ls2[0] = 100
ls2, ls

([100, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr2[0] = 100
arr2, arr

(array([100,   5,   6,   7]),
 array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9]))

In [55]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
# 提取第一行
arr2d[0]

array([1, 2, 3])

In [56]:
# 提取第一列
arr2d[:,0]

array([1, 4])

In [57]:
arr2d[0, 0]

1

In [58]:
arr2d[0:2, 0]

array([1, 4])

In [62]:
arr3d = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])

In [63]:
arr3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr3d[0]

array([1, 2, 3])

In [66]:
new_array = arr3d[0].copy() # 创建矩阵的新拷贝

In [67]:
new_array

array([1, 2, 3])

In [69]:
arr3d > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [72]:
subject = np.array(['chinese', 'math', 'chinese', 'english', 'history'])
df = np.random.randn(5, 3)
df

array([[ 0.25671595,  0.04356501,  0.30977807],
       [-0.90870105, -0.48161073,  2.70357573],
       [ 1.15681315,  1.24286729,  0.5603325 ],
       [-1.32091813,  0.86514563, -0.0238784 ],
       [ 0.08068096, -1.43820424, -2.56188224]])

In [74]:
# 假设每个subject都对应随机矩阵的一行
# 而我们想要提取出与chinese相对应的行
# 这里利用数组subject与字符‘chinese’的比较结果进行数组索引
subject == 'chinese'


array([ True, False,  True, False, False])

In [75]:
df[subject == 'chinese']

array([[0.25671595, 0.04356501, 0.30977807],
       [1.15681315, 1.24286729, 0.5603325 ]])

In [76]:
df[subject == 'chinese', 1:] # 去除第一列

array([[0.04356501, 0.30977807],
       [1.24286729, 0.5603325 ]])

In [77]:
df[subject == 'chinese', 2:] # 去除第一列和第二列

array([[0.30977807],
       [0.5603325 ]])

In [78]:
df[subject != 'chinese', 2:] 

array([[ 2.70357573],
       [-0.0238784 ],
       [-2.56188224]])

In [79]:
# 除了使用不等号 != 还表示否定
# 还可以使用波浪号 ~ 表示对条件结果的取反。
df[~(subject == 'chinese'), 2:]

array([[ 2.70357573],
       [-0.0238784 ],
       [-2.56188224]])

In [80]:
#通过布尔型数组索引可以
# 非常方便地对符合条件的数据进行重赋值，
# 这是数据分析最常用的操作之一
df[df < 0] = 0
df


array([[0.25671595, 0.04356501, 0.30977807],
       [0.        , 0.        , 2.70357573],
       [1.15681315, 1.24286729, 0.5603325 ],
       [0.        , 0.86514563, 0.        ],
       [0.08068096, 0.        , 0.        ]])

In [82]:
# 数据转置与轴转换
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [84]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [85]:
np.dot(arr, arr.T) # 内积

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [87]:
arr = np.arange(24).reshape((2, 3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr.transpose((1, 0, 2)) #  